DROP TABLE `accessAuditLog`;--> statement-breakpoint
DROP TABLE `accessInvitations`;--> statement-breakpoint
DROP TABLE `accessLinks`;--> statement-breakpoint
DROP TABLE `companies`;--> statement-breakpoint
DROP TABLE `companyAccessRequests`;--> statement-breakpoint
DROP TABLE `companyInfo`;--> statement-breakpoint
DROP TABLE `companyManagerCredentials`;--> statement-breakpoint
DROP TABLE `companyManagers`;--> statement-breakpoint
DROP TABLE `companyModuleCustomization`;--> statement-breakpoint
DROP TABLE `companySetupInvitations`;--> statement-breakpoint
DROP TABLE `companyValues`;--> statement-breakpoint
DROP TABLE `compliances`;--> statement-breakpoint
DROP TABLE `criticalityMatrix`;--> statement-breakpoint
DROP TABLE `documents`;--> statement-breakpoint
DROP TABLE `fodaAnalysis`;--> statement-breakpoint
DROP TABLE `indicators`;--> statement-breakpoint
DROP TABLE `managerCredentials`;--> statement-breakpoint
DROP TABLE `managerInvitations`;--> statement-breakpoint
DROP TABLE `operationalObjectives`;--> statement-breakpoint
DROP TABLE `passwordResetTokens`;--> statement-breakpoint
DROP TABLE `policies`;--> statement-breakpoint
DROP TABLE `policyObjectives`;--> statement-breakpoint
DROP TABLE `procedureRecords`;--> statement-breakpoint
DROP TABLE `procedures`;--> statement-breakpoint
DROP TABLE `processAccessKeys`;--> statement-breakpoint
DROP TABLE `processCharacterizations`;--> statement-breakpoint
DROP TABLE `processCompliances`;--> statement-breakpoint
DROP TABLE `processFODA`;--> statement-breakpoint
DROP TABLE `processIndicators`;--> statement-breakpoint
DROP TABLE `processLeaderCredentials`;--> statement-breakpoint
DROP TABLE `processLeaderInvitations`;--> statement-breakpoint
DROP TABLE `processLeaderPINResetTokens`;--> statement-breakpoint
DROP TABLE `processOwnerInvitations`;--> statement-breakpoint
DROP TABLE `processOwners`;--> statement-breakpoint
DROP TABLE `processParticipants`;--> statement-breakpoint
DROP TABLE `processResources`;--> statement-breakpoint
DROP TABLE `processRiskMatrices`;--> statement-breakpoint
DROP TABLE `processScheduleActivities`;--> statement-breakpoint
DROP TABLE `processTacticalObjectives`;--> statement-breakpoint
DROP TABLE `processTrainings`;--> statement-breakpoint
DROP TABLE `processUsers`;--> statement-breakpoint
DROP TABLE `processes`;--> statement-breakpoint
DROP TABLE `riskMatrix`;--> statement-breakpoint
DROP TABLE `stakeholderCriticalities`;--> statement-breakpoint
DROP TABLE `stakeholders`;--> statement-breakpoint
DROP TABLE `strategicObjectives`;--> statement-breakpoint
DROP TABLE `subprocessMapEntries`;--> statement-breakpoint
DROP TABLE `subprocessMapOutputs`;--> statement-breakpoint
DROP TABLE `subprocessMapSubprocesses`;--> statement-breakpoint
DROP TABLE `subprocessMaps`;--> statement-breakpoint
DROP TABLE `subprocesses`;--> statement-breakpoint
DROP TABLE `tacticalObjectives`;--> statement-breakpoint
DROP TABLE `trainings`;--> statement-breakpoint
DROP TABLE `userCompanyAccess`;